services:
  - type: web
    name: student-math-predictor
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app
